variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "eu-central-1"
}

variable "project" {
  description = "Project name used for resource naming"
  type        = string
  default     = "cs3"
}

variable "environment" {
  description = "Environment name (dev, prod)"
  type        = string
  default     = "dev"
}

variable "github_repo" {
  description = "GitHub repo for OIDC trust (format: owner/repo)"
  type        = string
  default     = "lainus-jpeg/cs3-portal"
}

# ── Networking ────────────────────────────────────────────────────────────────
variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.30.0.0/16"
}

variable "availability_zones" {
  description = "Availability zones to use"
  type        = list(string)
  default     = ["eu-central-1a", "eu-central-1b"]
}

variable "public_subnet_cidrs" {
  description = "CIDRs for public subnets (ALB, NAT Gateway)"
  type        = list(string)
  default     = ["10.30.0.0/24", "10.30.1.0/24"]
}

variable "private_subnet_cidrs" {
  description = "CIDRs for private subnets (EKS nodes)"
  type        = list(string)
  default     = ["10.30.10.0/24", "10.30.11.0/24"]
}

variable "db_subnet_cidrs" {
  description = "CIDRs for database subnets (RDS)"
  type        = list(string)
  default     = ["10.30.20.0/24", "10.30.21.0/24"]
}

variable "monitoring_subnet_cidrs" {
  description = "CIDRs for monitoring subnets (Prometheus, Grafana)"
  type        = list(string)
  default     = ["10.30.30.0/24", "10.30.31.0/24"]
}

# ── EKS ───────────────────────────────────────────────────────────────────────
variable "eks_node_instance_type" {
  description = "EC2 instance type for EKS nodes"
  type        = string
  default     = "t3.small"
}

variable "eks_desired_nodes" {
  description = "Desired number of EKS nodes"
  type        = number
  default     = 2
}

variable "eks_min_nodes" {
  description = "Minimum number of EKS nodes"
  type        = number
  default     = 1
}

variable "eks_max_nodes" {
  description = "Maximum number of EKS nodes"
  type        = number
  default     = 3
}

# ── RDS ───────────────────────────────────────────────────────────────────────
variable "db_name" {
  description = "PostgreSQL database name"
  type        = string
  default     = "cs3portal"
}

variable "db_username" {
  description = "PostgreSQL master username"
  type        = string
  default     = "cs3admin"
}
# db_password is auto-generated by the rds module — no variable needed

variable "jwt_secret" {
  description = "JWT signing secret for the portal backend"
  type        = string
  sensitive   = true
}

# ── ALB ───────────────────────────────────────────────────────────────────────
variable "certificate_arn" {
  description = "SSL certificate ARN for HTTPS (empty string for dev, set for production)"
  type        = string
  default     = ""
}

variable "rds_multi_az" {
  description = "Enable Multi-AZ for RDS (failover support)"
  type        = bool
  default     = false # set to true in prod for Phase 4 failover test
}

variable "grafana_admin_password" {
  description = "Admin password for Grafana dashboard"
  type        = string
  sensitive   = true
  default     = "Innovatech2025!"
}
